### ISSUE TITLE
Web UI Doesn't Update

### ISSUE THREAD

**Issue by maxmatthews** [BaReinhard/Multiroom-Audio-iOS#6]
When I run `node server.js` I get the default sinks listed in https://github.com/BaReinhard/Multiroom-Audio-iOS/blob/master/node/public/app/sinks.json not the actual sinks that the system is detecting.
I understand that this feature is a work in progress, but I think the readme should reflect that.
Also, completely side note, but this project is AMAZING. I've been looking for something to solve this exact problem for over a year and I'm so happy someone finally took the initiative to make it happen. Please let me know if I can help out at all. I'm the kind of person that opens a lot of issues, but with permission, I'll also make a lot of pull requests.

**Comment by BaReinhard** [comment]
I am open to all the help I can get, I have made quite a bit of changes since the last pull request. Tonight I actually have the time and will be creating a bit more working files for the project. I have created a couple scripts that will generate all the existing sinks and format them in a json string which will be saved in the app directory. I am currently working on a way to have the sinks.json file to update on each page load. I believe I have found a way using an http post request, but much of the code I have is just horrible looking and needs some sprucing up (since its just been debugging) . I am pretty new to angular so I'm sure there are better ways to do things so if you have the knowledge please feel free to share them with me via pull requests or other means. 

I am never shy of new issues (it's a good problem to have, as opposed to no traffic at all), so feel free to bring the issues. 👍🏼

**Comment by maxmatthews** [comment]
I'm not an angular developer myself, I perfer react. However I do know a bit of node. I'll let you finish up the current sprint of your work and then feel free to reach out to me or start a TODO list somewhere of tasks that I may be able to help out with.

**Comment by BaReinhard** [comment]
I am unfamiliar with react and actually just started learning angular last week so my knowledge is just forming on the subject. That being said I believe I have fixed the issue for things updating aside from one nagging issue, where the get request for the json string seems to occur before the post request for updating the sinks.json file. I should find a usable fix within the given week, but for now that is the only current issue. I have updated the node files and added some css just so its a bit more iOS like. Still working on my css skills as well, but I plan to have the UI look similar to the home screen on an ios device, but that will take some getting things ironed out.

if there are any things that you see wrong with the current project implementation or otherwise please let me know and use all the issues and pull requests you need.

**Comment by BaReinhard** [comment]
This issue has been fixed with the latest commits. Everything is now supported in the install script and will place everything in the correct locations. You should be able to start fresh on a new install then run the script. Upon reboot simply run `start_web_ui` and visit your pis address on port 2221 in your web browser. For now the sinks will update on the start of the web ui, to refresh them you will need to restart the web ui, via `pkill nodejs ` then `start_web_ui`. I will shortly implement a refresh button when I get more time.
